### ISSUE TITLE
Doesn't work with Sketch Workspace files

### ISSUE THREAD

**Issue by calebhaye** [keplerlab/genus#13]
I recently downloaded this plugin in an effort to see if it works.

I created a simple (A4) artboard, placed a few rectangles and some text, and tried to export.  

Unfortunately, I got the following error:
<img width="275" alt="Screen Shot 2021-07-26 at 2 33 14 PM" src="https://user-images.githubusercontent.com/107480/127062323-08473561-9325-46d8-8712-99f0f60eac62.png">

I nearly gave up on the plugin at that point, assuming it was just plain broken or otherwise not compatible with the latest version of Sketch (I'm using v 74.1).  However, since the whole concept of Sketch "Workspaces" was relatively new to me, I figured this plugin simply may not work with Workspace files.  So I created a simple document that lives on my local system, and the export worked great! 👍 

Then, to confirm my hunch, I created a simple doc that lived in a Sketch workspace and tried to export the same artboard I was able to export from a file that lived locally.  Unfortunately, that gave me the same (wonky) error.

So, based on my simple example, export does not work with files in Sketch workspaces.

**Comment by tmschafer** [comment]
Thank you @calebhaye! I was having the same issue and making the file local totally fixed it!

**Comment by thealokkr** [comment]
Closing as this is not an issue
