### ISSUE TITLE
Error when exporting

### ISSUE THREAD

**Issue by nyochumKE** [keplerlab/genus#22]
Error: Could not create output directory images. 
Failed to export 2D123A64-9A89-4BCA-814F-361152CBFF48
Could not create output directory images. 
Failed to export 2D123A64-9A89-4BCA-814F-361152CBFF48@2x
Could not create output directory images. 
Failed to export 2D123A64-9A89-4BCA-814F-361152CBFF48@3x

**Comment by ZJU-Try** [comment]
I have the same problem. How to resolve it?
