### ISSUE TITLE
Support OS Windows

### ISSUE THREAD

**Issue by Serjiios** [keplerlab/genus#4]
Hello.
It would be great if your plugin will support Windows OS. There is now a Lunacy app (https://icons8.com/lunacy) for this operating system that supports Sketch plugins.
Now I get an error when trying to export.
<img width="468" alt="ice_screenshot_20200929-123002" src="https://user-images.githubusercontent.com/48542030/94527996-3c2b2880-0251-11eb-871f-44c04fc34e20.png">
If you think that this is already an error that occurs due to the fault of Lunacy, then I will pass this information on to the Lunacy developers.

**Comment by mayank10j** [comment]
As of now we only support Sketch which is Mac-OS only, lots of sketch and sketch plugin functionality are heavily dependent on MacOS API, There is currently no Windows version of sketch and Sketch api, It might be good idea to contact Lunacy for this.
