### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by Digitmind** [keplerlab/genus#5]
I get the following error: 
Oops Something went wrong: You may want to an raise issue on github, Copy paste following message:
ReferenceError: Can't find variable: errorMessage

Any idea?

**Comment by bounty1342** [comment]
```
Oops Something went wrong: You may want to an raise issue on github, Copy paste following message:
TypeError: null is not an object (evaluating 'f.MSAttributedStringColorAttribute.hexValue')
```

Same here

**Comment by mayank10j** [comment]
Hi @Digitmind  and @bounty1342  can you paste more information about issue, so that i can replicate this issue. 
Like MacOS Version, Sketch version, and upload and send link of sketch file which triggered these issues.

**Comment by thealokkr** [comment]
Closing in absence of any details
