### ISSUE TITLE
Bad Plugin Error

### ISSUE THREAD

**Issue by wendellmeset** [keplerlab/genus#9]
Hi, so I'm going to try to give as much detail as I can:

My Error: "Error: The object has no suitable property or field named 'layerName'" 
Sketch Version: Latest (I also tried with latest version of icon8 lunacy for windows 10 latest which is compatible with sketch plugins and files)

How to reproduce: Create an artboard, put anything on it, click export html button from genus, see error
What I found out: Genus lets you export when the artboard is empty, but if i put stuff on it, it gives me the error, i'm guessing its something to do with layers

**Comment by wendellmeset** [comment]
@SamarthShah @rammurat @mayank10j @loxxy Sorry for ping, im on a time crunch with my website

**Comment by mayank10j** [comment]
@wendellmeset  Can you please mention your OS version and some if possible upload some test file, 
I am able to export without issue on sketch version 71.2 (115329) on MacOS Catalia 10.15.7.
Is your Mac Intel based or newer M1 ? 
As of now we don't support icon8 lunacy, as some of the genus sketch plugin features depends on Native MacOS API which are not available on windows.

**Comment by wendellmeset** [comment]
@mayank10j Hmm, i figured out its just an issue with the difference in layer management in icons8 lunacy, ill give this info directly to lunacy devs, im so sorry
